name: Create a preview deployment
# You might want to set up preview deployments for every pull request
on: pull_request

jobs:
  test-with-chalk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # The chalk-ai/deploy-action expects chalkpy to be installed
      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: chalk-ai/deploy-action@v2
        with:
          client-id: ${{secrets.CHALK_CLIENT_ID}}
          client-secret: ${{secrets.CHALK_CLIENT_SECRET}}
          # Creates a preview deployment with a unique deployment ID,
          # output by this step
          no-promote: true
          # Waits for the deployment to succeed
          await: true
