from enum import Enum


class ItemCategoryValueEnum(str, Enum):
    ARTS_AND_PHOTOGRAPHY = "Arts & Photography"
    BIOGRAPHIES_AND_MEMOIRS = "Biographies & Memoirs"
    BUSINESS_AND_MONEY = "Business & Money"
    CHILDRENS_BOOKS = "Children's Books"
    COMICS_AND_GRAPHIC_NOVELS = "Comics & Graphic Novels"
    COMPUTERS_AND_TECHNOLOGY = "Computers & Technology"
    COOKBOOKS_FOOD_AND_WINE = "Cookbooks, Food & Wine"
    CRAFTS_HOBBIES_AND_HOME = "Crafts, Hobbies & Home"
    EDUCATION_AND_TEACHING = "Education & Teaching"
    ENGINEERING_AND_TRANSPORTATION = "Engineering & Transportation"
    HEALTH_FITNESS_AND_DIETING = "Health, Fitness & Dieting"
    HISTORY = "History"
    HUMOR_AND_ENTERTAINMENT = "Humor & Entertainment"
    LAW = "Law"
    LITERATURE_AND_FICTION = "Literature & Fiction"
    MEDICAL_BOOKS = "Medical Books"
    MYSTERY_THRILLER_AND_SUSPENSE = "Mystery, Thriller & Suspense"
    PARENTING_AND_RELATIONSHIPS = "Parenting & Relationships"
    POLITICS_AND_SOCIAL_SCIENCES = "Politics & Social Sciences"
    REFERENCE = "Reference"
    RELIGION_AND_SPIRITUALITY = "Religion & Spirituality"
    ROMANCE = "Romance"
    SCIENCE_AND_MATH = "Science & Math"
    SCIENCE_FICTION_AND_FANTASY = "Science Fiction & Fantasy"
    SELF_HELP = "Self-Help"
    SPORTS_AND_OUTDOORS = "Sports & Outdoors"
    TEEN_AND_YOUNG_ADULT = "Teen & Young Adult"
    TEST_PREPARATION = "Test Preparation"
    TRAVEL = "Travel"
